### PR TITLE
added thumbprint for vmware 6.5 support

### PR DESCRIPTION
**Pull request by renoutg**
add the space separated vcthumbprint to your vmware plugin parameters (colon is in use)

### CODE REVIEW

**Comment by sduehr** [comment]
Hello Renout,

thanks for your contribution.

I've seen that you set
#define VSPHERE_DEFAULT_ADMIN_PORT 0
in bareos_vadp_dumper.cpp, why was that necesary?

Does it work for you like this with VDDK 5.5 against vSphere 6.5?
Did you test it with bareos filedaemon running on the VM so that hotadd transport is used automatically?

Regards,

Stephan

**Comment by sduehr** [comment]
Hello Renout,

I also noticed that you made the vcthumbprint option mandatory in the python code. Like this we can't integrate this with Bareos 16.2, as it would break existing working configurations.
I'd like to suggest, not to use blanks instead of colons for the config, but rather omit the colons in the config and add them for saving in the json file using something like this in the python code:

```
>>> thumbprint='E836581CCFB9BF46508699E77600997599813E45'
>>> ':'.join([thumbprint[i:i+2] for i in range(0, len(thumbprint), 2)])
'E8:36:58:1C:CF:B9:BF:46:50:86:99:E7:76:00:99:75:99:81:3E:45'
```

Also, the thumbprint can be retrieved by
echo -n | openssl s_client -connect vcserver.example.com:443 2>/dev/null | openssl x509 -noout -fingerprint -sha1

So the best approach is to leave the thumbprint as an optional parameter. The python plugin code should be changed to check the vSphere Version and decide if bareos_vadp_dumper needs the thumbprint or not. If it's needed but not in the config, the plugin should retrieve it and pass it to bareos_vadp_dumper.
I think most users would prefer to have the plugin retrieve the thumbprint, which may also change when the cert gets renewed. For additional security, optionally adding the thumbprint to the config should be possible.

Finally, there's no alternative to switching the VDDK to a newer version, as all VDDK release notes say:

"The VMware policy concerning backward and forward compatibility is for VDDK to support N-2 and N+1 releases."

That means, the currently used VDDK 5.5.4 only supports vSphere 5.1, 5.5 and 6.0, but not 6.5
See https://code.vmware.com/web/sdk/65/vddk for links to all VDDK release notes (also older versions).

So we should target this for Bareos 17.2, which also requires work to be done by starting to use branches in this code repo, which was not necesary until now. 

Regards,

Stephan

**Comment by renoutg** [comment]
> I've seen that you set
#define VSPHERE_DEFAULT_ADMIN_PORT 0
in bareos_vadp_dumper.cpp, why was that necesary?

I've had troubles connecting to the host to disable vmotion:

Log: VixDiskLibVim: Error 18000 (listener error GVmomiFaultInvalidResponse).
Warning: VixDiskLibVim: Login failure. Callback error 18000 at 2444.
Log: VixDiskLibVim: Failed to find the VM. Error 18000 at 2516.
Log: VixDiskLibVim: VixDiskLibVim_FreeNfcTicket: Free NFC ticket.
Log: VixDiskLib: VixDiskLib_PrepareForAccess: Disable Storage VMotion failed. Error 18000 (Cannot connect to the host) (fault (null), type GVmomiFaultInvalidResponse, reason: (none given), translated to 18000) at 4259.

when using 0 the port is selected by library (in my case 443). 902 should be selected when using nfc (hence the should). From vmware 6.0.1 there are different vars for soap and nfc: https://www.vmware.com/support/developer/vddk/vddk-601-releasenotes.html#whatsnew but that could result in backwards compatibility issues, but when creating a new branch version it could be considered.

> Does it work for you like this with VDDK 5.5 against vSphere 6.5?
Did you test it with bareos filedaemon running on the VM so that hotadd transport is used automatically?

Yes, I've compiled this against VMware-vix-disklib-6.5.0-4604867.x86_64

Yes, using hotadd
Log: VixDiskLib: VixDiskLib_GetInfo: Retrieve disk info.
Log: VixDiskLib: VixDiskLib_GetTransportMode: Retrieve transport mode.
Selected transport method: hotadd

**Comment by renoutg** [comment]
Assuming here a new branch for 6.5 would be created, the thumbprint is required. For me it doesn't matter if the fingerprint is fetched automatically or manual. Putting it in the config was more easier to implement and more secure.
The reason I used spaces is that I can just copy paste the fingerprint from my browser. I don't really prefer the one or the other, we just need something that works. And if you would create something that would fetch it automatically it even doesn't matter at all anymore I guess.

**Pull request merged**
